# Generated by Django 2.2.2 on 2019-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acctype',
        ),
        migrations.AlterField(
            model_name='user',
            name='acctext',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
