# Generated by Django 2.2.4 on 2019-09-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='icon'),
        ),
    ]
