# Generated by Django 2.2.2 on 2020-01-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acctype',
            field=models.CharField(choices=[('company', '企業アカウント'), ('general', '一般アカウント')], default='general', max_length=100),
        ),
    ]
