# Generated by Django 2.2.2 on 2020-01-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
        ('accounts', '0002_user_acctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uset_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
