# Generated by Django 2.2.2 on 2020-01-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
        ('accounts', '0003_user_uset_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uset_post',
        ),
        migrations.AddField(
            model_name='user',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='posts.Post'),
        ),
    ]
